# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-06 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('ingredients', models.CharField(max_length=256)),
                ('image_main', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('id_receipts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipts')),
            ],
        ),
    ]
