# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='receipts',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to=receipts.models.upload_image),
        ),
    ]
