# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-21 19:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
